services:
  - type: web
    name: inventory-lifecycle-manager-web
    runtime: node
    plan: free
    buildCommand: npm install && npm run setup && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: HOST
        value: "0.0.0.0"
      - key: PORT
        value: "3000"
      - key: MYSQL_HOST
        value: bhmk6xtbtqnenceak1r9-mysql.services.clever-cloud.com
      - key: MYSQL_PORT
        value: "3306"
      - key: MYSQL_USER
        value: uqnx9grycgwry6et
      - key: MYSQL_PASSWORD
        value: 2D64GOS0IAz2AcCsW1Te
      - key: MYSQL_DATABASE
        value: bhmk6xtbtqnenceak1r9
      - key: DATABASE_URL
        value: mysql://uqnx9grycgwry6et:2D64GOS0IAz2AcCsW1Te@bhmk6xtbtqnenceak1r9-mysql.services.clever-cloud.com:3306/bhmk6xtbtqnenceak1r9
      - key: VITE_BACKEND_API_URL
        value: https://inventory-lifecycle-manager-backend.onrender.com
      - key: SHOPIFY_API_KEY
        sync: false
      - key: SHOPIFY_API_SECRET
        sync: false
      - key: SCOPES
        sync: false
      - key: SHOPIFY_APP_URL
        sync: false
      - key: SHOPIFY_APP_NAME
        sync: false
      - key: SHOPIFY_API_VERSION
        value: "2026-10"
