# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3df39ce39e6e9a871e11d18b77897bb6"
application_url = "https://inventory-lifecycle-manager-web.onrender.com"
embedded = true
name = "Inventory Manager Dev"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_inventory,write_inventory,read_orders,write_orders,read_locations,read_markets_home,read_customers,write_customers,unauthenticated_read_product_tags,unauthenticated_read_product_listings"
optional_scopes = [ ]
use_legacy_install_flow = false

[product.metafields.app.demo_info]
type = "single_line_text_field"
name = "Demo Source Info"
description = "Tracks products created by the Shopify app template for development"

  [product.metafields.app.demo_info.access]
  admin = "merchant_read_write"

[metaobjects.app.example]
name = "Example"
description = "An example metaobject definition created by this template"

  [metaobjects.app.example.access]
  admin = "merchant_read_write"

[metaobjects.app.example.fields.title]
name = "Title"
type = "single_line_text_field"
required = true

[metaobjects.app.example.fields.description]
name = "Description"
type = "multi_line_text_field"

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]

  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]
  uri = "https://inventory-lifecycle-manager-backend.onrender.com/api/shopify/webhook"


  [[webhooks.subscriptions]]
  uri = "/webhooks/inventory_levels/update"
  topics = [ "inventory_levels/update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/products/update"
  topics = [ "products/update" ]

[auth]
redirect_urls = [
  "https://inventory-lifecycle-manager-web.onrender.com/auth/callback",
  "https://inventory-lifecycle-manager-web.onrender.com/auth/shopify/callback",
  "https://inventory-lifecycle-manager-web.onrender.com/api/auth/callback"
]

[build]
automatically_update_urls_on_dev = true
