# Learn more about configuring your app at:
# https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3df39ce39e6e9a871e11d18b77897bb6"

application_url = "https://inventory-lifecycle-manager-web.onrender.com"

embedded = true

name = "Inventory Manager Dev"

[access_scopes]

scopes = "read_customers,read_inventory,read_locations,read_markets_home,read_orders,read_products,unauthenticated_read_product_listings,unauthenticated_read_product_tags,write_customers,write_inventory,write_orders,write_products"

optional_scopes = []

use_legacy_install_flow = false

[build]
automatically_update_urls_on_dev = true

[webhooks]

api_version = "2026-07"

[events]

api_version = "unstable"

[[events.subscription]]

handle = "product-event"
topic = "Product"
actions = ["update"]
uri = "https://inventory-lifecycle-manager-backend.onrender.com/events"


[[webhooks.subscriptions]]

uri = "https://inventory-lifecycle-manager-backend.onrender.com/api/webhooks/inventory_levels/update"

topics = ["inventory_levels/update"]


[[webhooks.subscriptions]]

uri = "https://inventory-lifecycle-manager-backend.onrender.com/api/webhooks/orders/create"

topics = ["orders/create"]


[[webhooks.subscriptions]]

uri = "https://inventory-lifecycle-manager-backend.onrender.com/api/webhooks/products/update"

topics = ["products/update"]


[[webhooks.subscriptions]]

compliance_topics = [
  "customers/data_request",
  "customers/redact",
  "shop/redact"
]

topics = ["app/uninstalled"]

uri = "https://inventory-lifecycle-manager-backend.onrender.com/api/webhooks/app-uninstalled"

[auth]

redirect_urls = []


